var arr = [];

arr.push({ id: 'accesstoken', type: 'string', value: GUID(30), name: 'accesstoken', dtcreated: NOW });
arr.push({ id: 'auth_cookie', type: 'string', value: GUID(10), name: 'auth_cookie', dtcreated: NOW });
arr.push({ id: 'auth_secret', type: 'string', value: GUID(10), name: 'auth_secret', dtcreated: NOW });
arr.push({ id: 'cdn', type: 'string', value: '//cdn.componentator.com', name: 'cdn', dtcreated: NOW });
arr.push({ id: 'allow_custom_titles', type: 'boolean', value: 'true', name: 'allow_custom_titles', dtcreated: NOW });
arr.push({ id: 'allowappearance', type: 'boolean', value: 'true', name: 'allowappearance', dtcreated: NOW });
arr.push({ id: 'allowbackground', type: 'boolean', value: 'true', name: 'allowbackground', dtcreated: NOW });
arr.push({ id: 'allowpassword', type: 'boolean', value: 'true', name: 'allowpassword', dtcreated: NOW });
arr.push({ id: 'allowclock', type: 'boolean', value: 'true', name: 'allowclock', dtcreated: NOW });
arr.push({ id: 'allowcreate', type: 'string', value: '', name: 'allowcreate', dtcreated: NOW });
arr.push({ id: 'allowdesktop', type: 'boolean', value: 'true', name: 'allowdesktop', dtcreated: NOW });
arr.push({ id: 'allowdesktopfluid', type: 'boolean', value: 'true', name: 'allowdesktopfluid', dtcreated: NOW });
arr.push({ id: 'allowmembers', type: 'boolean', value: 'true', name: 'allowmembers', dtcreated: NOW });
arr.push({ id: 'allownickname', type: 'boolean', value: 'true', name: 'allownickname', dtcreated: NOW });
arr.push({ id: 'allownotifications', type: 'boolean', value: 'true', name: 'allownotifications', dtcreated: NOW });
arr.push({ id: 'allowprofile', type: 'boolean', value: 'true', name: 'allowprofile', dtcreated: NOW });
arr.push({ id: 'allowsmembers', type: 'boolean', value: 'false', name: 'allowsmembers', dtcreated: NOW });
arr.push({ id: 'allowstatus', type: 'boolean', value: 'true', name: 'allowstatus', dtcreated: NOW });
arr.push({ id: 'allowtheme', type: 'boolean', value: 'true', name: 'allowtheme', dtcreated: NOW });
arr.push({ id: 'allowaccesstoken', type: 'boolean', value: 'true', name: 'allowaccesstoken', dtcreated: NOW });
arr.push({ id: 'allowoauth', type: 'boolean', value: 'true', name: 'allowoauth', dtcreated: NOW });
arr.push({ id: 'background', type: 'string', value: '', name: 'background', dtcreated: NOW });
arr.push({ id: 'colorscheme', type: 'string', value: '#4285f4', name: 'colorscheme', dtcreated: NOW });
arr.push({ id: 'cookie_expiration', type: 'string', value: '3 days', name: 'cookie_expiration', dtcreated: NOW });
arr.push({ id: 'defaultappid', type: 'string', value: '', name: 'defaultappid', dtcreated: NOW });
arr.push({ id: 'email', type: 'string', value: 'info@totaljs.com', name: 'email', dtcreated: NOW });
arr.push({ id: 'guest', type: 'boolean', value: 'false', name: 'guest', dtcreated: NOW });
arr.push({ id: 'marketplace', type: 'string', value: 'https://marketplace.openplatform.cloud', name: 'marketplace', dtcreated: NOW });
arr.push({ id: 'maxmembers', type: 'number', value: '10', name: 'maxmembers', dtcreated: NOW });
arr.push({ id: 'name', type: 'string', value: 'OpenPlatform', name: 'name', dtcreated: NOW });
arr.push({ id: 'mode', type: 'string', value: 'dev', name: 'mode', dtcreated: NOW });
arr.push({ id: 'sender', type: 'string', value: 'info@totaljs.com', name: 'sender', dtcreated: NOW });
arr.push({ id: 'smtp', type: 'string', value: 'localhost', name: 'smtp', dtcreated: NOW });
arr.push({ id: 'smtpsettings', type: 'json', value: '{"user":"","password":"","timeout":2000}', name: 'smtpsettings', dtcreated: NOW });
arr.push({ id: 'test', type: 'boolean', value: 'true', name: 'test', dtcreated: NOW });
arr.push({ id: 'url', type: 'string', value: 'https://YOURDOMAIN.com', name: 'url', dtcreated: NOW });
arr.push({ id: 'verifytoken', type: 'string', value: GUID(25), name: 'verifytoken', dtcreated: NOW });
arr.push({ id: 'welcome', type: 'string', value: '', name: 'welcome', dtcreated: NOW });

var db = DBMS();

// Configuration
for (var i = 0; i < arr.length; i++)
	db.insert('config', arr[i]);

// Languages
arr = [];

arr.push({ id: 'zu', name: 'Zulu', spoken: 'isiZulu' });
arr.push({ id: 'zh', name: 'Chinese', spoken: '中文、汉语、漢語' });
arr.push({ id: 'za', name: 'Zhuang', spoken: 'Saɯ cueŋƅ; Saw cuengh' });
arr.push({ id: 'yo', name: 'Yoruba', spoken: 'Yorùbá' });
arr.push({ id: 'yi', name: 'Yiddish', spoken: 'ייִדיש' });
arr.push({ id: 'xh', name: 'Xhosa', spoken: 'isiXhosa' });
arr.push({ id: 'wo', name: 'Wolof', spoken: 'Wollof' });
arr.push({ id: 'wa', name: 'Walloon', spoken: 'Walon' });
arr.push({ id: 'vo', name: 'Volapük', spoken: 'Volapük' });
arr.push({ id: 'vi', name: 'Vietnamese', spoken: 'Tiếng Việt' });
arr.push({ id: 've', name: 'Venda', spoken: 'tshiVenḓa' });
arr.push({ id: 'uz', name: 'Uzbek', spoken: 'O\'zbek; Ўзбек; أۇزبېك' });
arr.push({ id: 'ur', name: 'Urdu', spoken: 'اردو' });
arr.push({ id: 'uk', name: 'Ukrainian', spoken: 'українська мова' });
arr.push({ id: 'ug', name: 'Uighur', spoken: 'Uyƣurqə; ئۇيغۇرچ ' });
arr.push({ id: 'ty', name: 'Tahitian', spoken: 'Reo Mā`ohi' });
arr.push({ id: 'tw', name: 'Twi', spoken: 'Twi' });
arr.push({ id: 'tt', name: 'Tatar', spoken: 'татарча; tatarça; تاتارچا' });
arr.push({ id: 'ts', name: 'Tsonga', spoken: 'xiTsonga' });
arr.push({ id: 'tr', name: 'Turkish', spoken: 'Türkçe' });
arr.push({ id: 'to', name: 'Tonga', spoken: 'faka Tonga' });
arr.push({ id: 'tn', name: 'Tswana', spoken: 'seTswana' });
arr.push({ id: 'tl', name: 'Tagalog', spoken: 'Tagalog' });
arr.push({ id: 'tk', name: 'Turkmen', spoken: 'Türkmen; Түркмен' });
arr.push({ id: 'ti', name: 'Tigrinya', spoken: 'ትግርኛ' });
arr.push({ id: 'th', name: 'Thai', spoken: 'ไทย' });
arr.push({ id: 'tg', name: 'Tajik', spoken: 'тоҷикӣ; toğikī; تاجیکی' });
arr.push({ id: 'te', name: 'Telugu', spoken: 'తెలుగు' });
arr.push({ id: 'ta', name: 'Tamil', spoken: 'தமிழ்' });
arr.push({ id: 'sw', name: 'Swahili', spoken: 'Kiswahili' });
arr.push({ id: 'sv', name: 'Swedish', spoken: 'Svenska' });
arr.push({ id: 'su', name: 'Sundanese', spoken: 'Basa Sunda' });
arr.push({ id: 'st', name: 'Southern Sotho', spoken: 'seSotho' });
arr.push({ id: 'ss', name: 'Swati', spoken: 'SiSwati' });
arr.push({ id: 'sr', name: 'Serbian', spoken: 'српски језик' });
arr.push({ id: 'sq', name: 'Albanian', spoken: 'Shqip' });
arr.push({ id: 'so', name: 'Somali', spoken: 'Soomaaliga; af Soomaali' });
arr.push({ id: 'sn', name: 'Shona', spoken: 'chiShona' });
arr.push({ id: 'sm', name: 'Samoan', spoken: 'gagana fa\'a Samoa' });
arr.push({ id: 'sl', name: 'Slovenian', spoken: 'slovenščina' });
arr.push({ id: 'sk', name: 'Slovak', spoken: 'slovenčina' });
arr.push({ id: 'si', name: 'Sinhala', spoken: 'සිංහල' });
arr.push({ id: 'sh', name: 'Serbo-Croatian', spoken: 'Српскохрватски' });
arr.push({ id: 'sg', name: 'Sango', spoken: 'yângâ tî sängö' });
arr.push({ id: 'se', name: 'Northern Sami', spoken: 'Davvisámegiella' });
arr.push({ id: 'sd', name: 'Sindhi', spoken: 'सिन्धी; سنڌي، سندھی' });
arr.push({ id: 'sc', name: 'Sardinian', spoken: 'sardu' });
arr.push({ id: 'sa', name: 'Sanskrit', spoken: 'संस्कृतम्' });
arr.push({ id: 'rw', name: 'Kinyarwanda', spoken: 'Kinyarwanda' });
arr.push({ id: 'ru', name: 'Russian', spoken: 'русский язык' });
arr.push({ id: 'ro', name: 'Romanian', spoken: 'română' });
arr.push({ id: 'rn', name: 'Kirundi', spoken: 'kiRundi' });
arr.push({ id: 'rm', name: 'Raeto-Romance', spoken: 'rumantsch grischun' });
arr.push({ id: 'qu', name: 'Quechua', spoken: 'Runa Simi; Kichwa' });
arr.push({ id: 'pt', name: 'Portuguese', spoken: 'Português' });
arr.push({ id: 'ps', name: 'Pashto', spoken: 'پښتو' });
arr.push({ id: 'pl', name: 'Polish', spoken: 'Polski' });
arr.push({ id: 'pi', name: 'Pāli', spoken: 'पाऴि' });
arr.push({ id: 'pa', name: 'Panjabi', spoken: 'ਪੰਜਾਬੀ; پنجابی' });
arr.push({ id: 'os', name: 'Ossetian', spoken: 'Ирон æвзаг' });
arr.push({ id: 'or', name: 'Oriya', spoken: 'ଓଡ଼ିଆ' });
arr.push({ id: 'om', name: 'Oromo', spoken: 'Afaan Oromoo' });
arr.push({ id: 'oj', name: 'Ojibwa', spoken: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' });
arr.push({ id: 'oc', name: 'Occitan', spoken: 'Occitan' });
arr.push({ id: 'ny', name: 'Chichewa', spoken: 'chiCheŵa; chinyanja' });
arr.push({ id: 'nv', name: 'Navajo', spoken: 'Diné bizaad; Dinékʼehǰí' });
arr.push({ id: 'nr', name: 'South Ndebele', spoken: 'Ndébélé' });
arr.push({ id: 'no', name: 'Norwegian', spoken: 'Norsk' });
arr.push({ id: 'nn', name: 'Norwegian Nynorsk', spoken: 'Nynorsk' });
arr.push({ id: 'nl', name: 'Dutch', spoken: 'Nederlands' });
arr.push({ id: 'ng', name: 'Ndonga', spoken: 'Owambo' });
arr.push({ id: 'ne', name: 'Nepali', spoken: 'नेपाली' });
arr.push({ id: 'nd', name: 'North Ndebele', spoken: 'isiNdebele' });
arr.push({ id: 'nb', name: 'Norwegian Bokmål', spoken: 'Norsk (bokmål)' });
arr.push({ id: 'na', name: 'Nauru', spoken: 'Ekakairũ Naoero' });
arr.push({ id: 'my', name: 'Burmese', spoken: 'မ္ရန္‌မာစကား (Myanma zaga)' });
arr.push({ id: 'mt', name: 'Maltese', spoken: 'Malti' });
arr.push({ id: 'ms', name: 'Malay', spoken: 'bahasa Melayu; بهاس ملايو' });
arr.push({ id: 'mr', name: 'Marathi', spoken: 'मराठी' });
arr.push({ id: 'mo', name: 'Moldavian', spoken: 'лимба молдовеняскэ' });
arr.push({ id: 'mn', name: 'Mongolian', spoken: 'Монгол' });
arr.push({ id: 'ml', name: 'Malayalam', spoken: 'മലയാളം' });
arr.push({ id: 'mk', name: 'Macedonian', spoken: 'македонски јазик' });
arr.push({ id: 'mi', name: 'Māori', spoken: 'te reo Māori' });
arr.push({ id: 'mh', name: 'Marshallese', spoken: 'Kajin M̧ajeļ' });
arr.push({ id: 'mg', name: 'Malagasy', spoken: 'Malagasy fiteny' });
arr.push({ id: 'lv', name: 'Latvian', spoken: 'latviešu valoda' });
arr.push({ id: 'lu', name: 'Luba-Katanga', spoken: 'luba' });
arr.push({ id: 'lt', name: 'Lithuanian', spoken: 'lietuvių kalba' });
arr.push({ id: 'lo', name: 'Lao', spoken: 'ພາສາລາວ' });
arr.push({ id: 'ln', name: 'Lingala', spoken: 'Lingála' });
arr.push({ id: 'li', name: 'Limburgish', spoken: 'Limburgs' });
arr.push({ id: 'lg', name: 'Ganda', spoken: 'Luganda' });
arr.push({ id: 'lb', name: 'Luxembourgish', spoken: 'Lëtzebuergesch' });
arr.push({ id: 'la', name: 'latin', spoken: 'latine; lingua latina' });
arr.push({ id: 'ky', name: 'Kirghiz', spoken: 'кыргыз тили' });
arr.push({ id: 'kw', name: 'Cornish', spoken: 'Kernewek' });
arr.push({ id: 'kv', name: 'Komi', spoken: 'коми кыв' });
arr.push({ id: 'ku', name: 'Kurdish', spoken: 'Kurdî; كوردی' });
arr.push({ id: 'ks', name: 'Kashmiri', spoken: 'कश्मीरी; كشميري' });
arr.push({ id: 'kr', name: 'Kanuri', spoken: 'Kanuri' });
arr.push({ id: 'ko', name: 'Korean', spoken: '한국어 (韓國語); 조선말 (朝鮮語)' });
arr.push({ id: 'kn', name: 'Kannada', spoken: 'ಕನ್ನಡ' });
arr.push({ id: 'km', name: 'Khmer', spoken: 'ភាសាខ្មែរ' });
arr.push({ id: 'kl', name: 'Kalaallisut', spoken: 'kalaallisut; kalaallit oqaasii' });
arr.push({ id: 'kk', name: 'Kazakh', spoken: 'Қазақ тілі' });
arr.push({ id: 'kj', name: 'Kuanyama', spoken: 'Kuanyama' });
arr.push({ id: 'ki', name: 'Kikuyu', spoken: 'Gĩkũyũ' });
arr.push({ id: 'kg', name: 'Kongo', spoken: 'KiKongo' });
arr.push({ id: 'ka', name: 'Georgian', spoken: 'ქართული' });
arr.push({ id: 'jv', name: 'Javanese', spoken: 'basa Jawa' });
arr.push({ id: 'ja', name: 'Japanese', spoken: '日本語 (にほんご)' });
arr.push({ id: 'iu', name: 'Inuktitut', spoken: 'ᐃᓄᒃᑎᑐᑦ' });
arr.push({ id: 'it', name: 'Italian', spoken: 'Italiano' });
arr.push({ id: 'is', name: 'Icelandic', spoken: 'Íslenska' });
arr.push({ id: 'io', name: 'Ido', spoken: 'Ido' });
arr.push({ id: 'ik', name: 'Inupiaq', spoken: 'Iñupiaq; Iñupiatun' });
arr.push({ id: 'ii', name: 'Sichuan Yi', spoken: 'ꆇꉙ' });
arr.push({ id: 'ig', name: 'Igbo', spoken: 'Igbo' });
arr.push({ id: 'ie', name: 'Interlingue', spoken: 'Interlingue' });
arr.push({ id: 'id', name: 'Indonesian', spoken: 'Bahasa Indonesia' });
arr.push({ id: 'ia', name: 'Interlingua', spoken: 'Interlingua' });
arr.push({ id: 'hz', name: 'Herero', spoken: 'Otjiherero' });
arr.push({ id: 'hy', name: 'Armenian', spoken: 'Հայերեն' });
arr.push({ id: 'hu', name: 'Hungarian', spoken: 'Magyar' });
arr.push({ id: 'ht', name: 'Haitian', spoken: 'Kreyòl ayisyen' });
arr.push({ id: 'hr', name: 'Croatian', spoken: 'Hrvatski' });
arr.push({ id: 'ho', name: 'Hiri Motu', spoken: 'Hiri Motu' });
arr.push({ id: 'hi', name: 'Hindi', spoken: 'हिन्दी' });
arr.push({ id: 'he', name: 'Hebrew', spoken: 'עברית' });
arr.push({ id: 'ha', name: 'Hausa', spoken: 'هَوُسَ' });
arr.push({ id: 'gv', name: 'Manx', spoken: 'Ghaelg' });
arr.push({ id: 'gu', name: 'Gujarati', spoken: 'ગુજરાતી' });
arr.push({ id: 'gn', name: 'Guaraní', spoken: 'Avañe\'ẽ' });
arr.push({ id: 'gl', name: 'Galician', spoken: 'Galego' });
arr.push({ id: 'gd', name: 'Gaelic', spoken: 'Gàidhlig' });
arr.push({ id: 'ga', name: 'Irish', spoken: 'Gaeilge' });
arr.push({ id: 'fy', name: 'Western Frisian', spoken: 'Frysk' });
arr.push({ id: 'fr', name: 'French', spoken: 'français; langue française' });
arr.push({ id: 'fo', name: 'Faroese', spoken: 'Føroyskt' });
arr.push({ id: 'fj', name: 'Fijian', spoken: 'vosa Vakaviti' });
arr.push({ id: 'fi', name: 'Finnish', spoken: 'Suomen kieli' });
arr.push({ id: 'ff', name: 'Fulah', spoken: 'Fulfulde' });
arr.push({ id: 'fa', name: 'Persian', spoken: 'فارسی' });
arr.push({ id: 'eu', name: 'Basque', spoken: 'euskara' });
arr.push({ id: 'et', name: 'Estonian', spoken: 'Eesti keel' });
arr.push({ id: 'es', name: 'Spanish', spoken: 'español; castellano' });
arr.push({ id: 'eo', name: 'Esperanto', spoken: 'Esperanto' });
arr.push({ id: 'en', name: 'English', spoken: 'English' });
arr.push({ id: 'el', name: 'Greek', spoken: 'Ελληνικά' });
arr.push({ id: 'ee', name: 'Ewe', spoken: 'Ɛʋɛgbɛ' });
arr.push({ id: 'dz', name: 'Dzongkha', spoken: 'རྫོང་ཁ' });
arr.push({ id: 'dv', name: 'Divehi', spoken: 'ދިވެހި' });
arr.push({ id: 'de', name: 'German', spoken: 'Deutsch' });
arr.push({ id: 'da', name: 'Danish', spoken: 'dansk' });
arr.push({ id: 'cy', name: 'Welsh', spoken: 'Cymraeg' });
arr.push({ id: 'cv', name: 'Chuvash', spoken: 'чӑваш чӗлхи' });
arr.push({ id: 'cu', name: 'Church Slavic', spoken: 'словѣньскъ ѩꙁꙑкъ' });
arr.push({ id: 'cs', name: 'Czech', spoken: 'čeština' });
arr.push({ id: 'cr', name: 'Cree', spoken: 'ᓀᐦᐃᔭᐍᐏᐣ' });
arr.push({ id: 'co', name: 'Corsican', spoken: 'corsu; lingua corsa' });
arr.push({ id: 'ch', name: 'Chamorro', spoken: 'Chamoru' });
arr.push({ id: 'ce', name: 'Chechen', spoken: 'нохчийн мотт' });
arr.push({ id: 'ca', name: 'Catalan', spoken: 'Català' });
arr.push({ id: 'bs', name: 'Bosnian', spoken: 'bosanski jezik' });
arr.push({ id: 'br', name: 'Breton', spoken: 'brezhoneg' });
arr.push({ id: 'bo', name: 'Tibetan', spoken: 'བོད་ཡིག' });
arr.push({ id: 'bn', name: 'Bengali', spoken: 'বাংলা' });
arr.push({ id: 'bm', name: 'Bambara', spoken: 'bamanankan' });
arr.push({ id: 'bi', name: 'Bislama', spoken: 'Bislama' });
arr.push({ id: 'bh', name: 'Bihari', spoken: 'भोजपुरी' });
arr.push({ id: 'bg', name: 'Bulgarian', spoken: 'български език' });
arr.push({ id: 'be', name: 'Belarusian', spoken: 'Беларуская' });
arr.push({ id: 'ba', name: 'Bashkir', spoken: 'башҡорт теле' });
arr.push({ id: 'az', name: 'Azerbaijani', spoken: 'azərbaycan dili' });
arr.push({ id: 'ay', name: 'Aymara', spoken: 'aymar aru' });
arr.push({ id: 'av', name: 'Avaric', spoken: 'авар мацӀ; магӀарул мацӀ' });
arr.push({ id: 'as', name: 'Assamese', spoken: 'অসমীয়া' });
arr.push({ id: 'ar', name: 'Arabic', spoken: 'العربية' });
arr.push({ id: 'an', name: 'Aragonese', spoken: 'Aragonés' });
arr.push({ id: 'am', name: 'Amharic', spoken: 'አማርኛ' });
arr.push({ id: 'ak', name: 'Akan', spoken: 'Akan' });
arr.push({ id: 'af', name: 'Afrikaans', spoken: 'Afrikaans' });
arr.push({ id: 'ae', name: 'Avestan', spoken: 'avesta' });
arr.push({ id: 'ab', name: 'Abkhaz', spoken: 'Аҧсуа' });
arr.push({ id: 'aa', name: 'Afar', spoken: 'Afaraf' });

// Configuration
for (var i = 0; i < arr.length; i++) {
	arr[i].active = true;
	db.insert('languages', arr[i]);
}